### PR TITLE
[318] added quickpick asking which deployment type to add to user

### LINKED ISSUE #318: [critical] add deployment for zipped files impossible on windows
On windows, the file-picker dialog can only open either in file mode or folder mode. Despite hte API allowing flags to allow each of file or folder, and despite this working fine on other OSes, it does not work on windows. 

Windows can currently only pick folders. This isn't good. 

Possible solutions:
1) Have two separate actions (add file deployment, add exploded deployment) to initiate two similar workflows but exchange the file picker dialog properly
2) Keep just the one action, but present the user with a quickpick to indicate before the dialog appears whether they want to pick a file or a folder. 

This is pretty bad, and our QE somehow missed it.

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #318 

Imho it's way better to add a quickpick than adding new actions to the context menu, we risk to make it unnecessarily long. 

Signed-off-by: Luca Stocchi lstocchi@redhat.com

### CODE REVIEW

File: src/serverExplorer.ts [hunk 1]
```diff
@@ -115,12 +115,23 @@ export class ServersViewTreeDataProvider implements TreeDataProvider< Protocol.S
         view.reveal(data, { focus: true, select: true });
     }
 
-    public addDeployment(server: Protocol.ServerHandle): Thenable<Protocol.Status> {
+    public async addDeployment(server: Protocol.ServerHandle): Promise<Protocol.Status> {
+        // quickpick to solve a vscode api bug in windows that only opens file-picker dialog either in file or folder mode
+        const isWindows: boolean = process.platform.indexOf('win') >= 0;
+        let filePickerType = 'file or exploded';
```
Comment (adietish) [inline src/serverExplorer.ts]: This methods gets rather lengthy (it already was but is now even more). I'd thus suggest to extract the windows specific part to it's own method (ex. #quickpickDeploymentType)

File: src/serverExplorer.ts [hunk 2]
```diff
@@ -115,12 +115,23 @@ export class ServersViewTreeDataProvider implements TreeDataProvider< Protocol.S
...
+            }
+        }
+
         return window.showOpenDialog({
-            canSelectFiles: true,
+            canSelectFiles: (isWindows ? filePickerType === 'File' : true),
             canSelectMany: false,
-            canSelectFolders: true,
-            openLabel: 'Select Deployment file or folder'
+            canSelectFolders: (isWindows ? filePickerType === 'Exploded' : true),
```
Comment (adietish) [inline src/serverExplorer.ts]: I'd also extract the string 'Exploded' to an enum (?) and reuse it for the quickpick so that you dont have to repeat yourself.

File: src/serverExplorer.ts (hunk 1 above)
Comment (lstocchi) [reply src/serverExplorer.ts]: I don't fully understand your suggestion. it doesn't seem to me we can extract much of the code to another method. Look at the last commit. This is the solution that maintains the code most readable possible for me.

Comment (adietish) [reply src/serverExplorer.ts]: works perfectly for me, great way to separate things, too.
