### PR TITLE
[313] Error "Connection is closed" wont tell the user what exactly and why it failed

### LINKED ISSUE #313: Error "Connection is closed" wont tell the user what exactly and why it failed
steps: 
1. ASSERT: have extension (and server) running
1. EXEC: kill server (felix)
1. EXEC: Try to add local/download server

Result:
image

Expected result:
The error should repeat the operation that failed and state the cause. It could say something like "Could not create a server, extension backend could not be contacted"
We should possibly also display a dialog when the rsp-server dies unexpectedly (and not just error when an operation is invoked).

This is related to #313 
This is related to #176

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #313 

Signed-off-by: Luca Stocchi lstocchi@redhat.com

### CODE REVIEW

**Comment by adietish** [comment]
immproves the errors niceley. Here's how the connection closed error is now displayed:
image

File: src/extension.ts [hunk 1]
```diff
@@ -130,8 +131,15 @@ function displayLog(outputPanel: vscode.OutputChannel, message: string, show: bo
 }
 
 function executeCommand(command: (...args: any[]) => Promise<any>, thisArg: any, ...params: any[]) {
+    const errorMessage = params[params.length - 1];
```
Comment (adietish) [inline src/extension.ts]: how can we be sure that the last entry in this array is a string message? 
To me this looks fragile and error-prone (what if a latter developer who's new to the project would pass in some object? Can't we use types to avoid such errors?

File: src/extension.ts [hunk 2]
```diff
@@ -130,8 +131,15 @@ function displayLog(outputPanel: vscode.OutputChannel, message: string, show: bo
...
     return command.call(thisArg, ...params).catch((err: string | Error) => {
         const error = typeof err === 'string' ? new Error(err) : err;
-        vscode.window.showErrorMessage(error.message);
+        let msg = error.message;
+        if (typeof err !== 'string') {
+            msg = `${errorMessage} Extension backend error - ${msg.toLowerCase()}`;
+        } else {
+            msg = `${errorMessage} ${msg.toLowerCase()}`;
```
Comment (adietish) [inline src/extension.ts]: why is no 'Extension backend error' added if err is not a string?

File: src/extension.ts [hunk 3]
```diff
@@ -59,33 +59,34 @@ async function initClient(serverInfo: server.ServerInfo): Promise<RSPClient> {
...
+            context => executeCommand(commandHandler.debugServer, commandHandler, context, errorMessage.replace('%ACTION%', 'debug'))),
         vscode.commands.registerCommand('server.stop',
-            context => executeCommand(commandHandler.stopServer, commandHandler, context)),
+            context => executeCommand(commandHandler.stopServer, commandHandler, context, errorMessage.replace('%ACTION%', 'stop'))),
         vscode.commands.registerCommand('server.remove',
-            context => executeCommand(commandHandler.removeServer, commandHandler, context)),
+            context => executeCommand(commandHandler.removeServer, commandHandler, context, errorMessage.replace('%ACTION%', 'remove'))),
         vscode.commands.registerCommand('server.output',
-            context => executeCommand(commandHandler.showServerOutput, commandHandler, context)),
+            context => executeCommand(commandHandler.showServerOutput, commandHandler, context, '')),
```
Comment (adietish) [inline src/extension.ts]: Shouldn't we add an error message here?

File: src/extension.ts [hunk 4]
```diff
@@ -59,33 +59,34 @@ async function initClient(serverInfo: server.ServerInfo): Promise<RSPClient> {
...
+            context => executeCommand(commandHandler.fullPublishServer, commandHandler, context, errorMessage.replace('%ACTION%', 'publish to'))),
         vscode.commands.registerCommand('server.createServer',
-            () => executeCommand(commandHandler.createServer, commandHandler)),
+            () => executeCommand(commandHandler.createServer, commandHandler, errorMessage.replace('%ACTION%', 'create'))),
         vscode.commands.registerCommand('server.addLocation',
-            () => executeCommand(commandHandler.addLocation, commandHandler)),
+            () => executeCommand(commandHandler.addLocation, commandHandler, 'Unable to detect any server: ')),
         vscode.commands.registerCommand('server.downloadRuntime',
-            () => executeCommand(commandHandler.downloadRuntime, commandHandler)),
+            () => executeCommand(commandHandler.downloadRuntime, commandHandler, 'Unable to download the runtime: ')),
```
Comment (adietish) [inline src/extension.ts]: I think that we should always talk of server to the user to be consistent.
Alternatively we should also talk of a runtime in the case right above ```Unable to detect any runtime:```

File: src/extension.ts [hunk 5]
```diff
@@ -59,33 +59,34 @@ async function initClient(serverInfo: server.ServerInfo): Promise<RSPClient> {
...
         vscode.commands.registerCommand('server.infoServer',
-            context => executeCommand(commandHandler.infoServer, commandHandler, context)),
+            context => executeCommand(commandHandler.infoServer, commandHandler, context, '')),
```
Comment (adietish) [inline src/extension.ts]: shouldn't we also specify what went wrong here?

File: src/extension.ts [hunk 6]
```diff
@@ -130,8 +131,15 @@ function displayLog(outputPanel: vscode.OutputChannel, message: string, show: bo
 }
 
 function executeCommand(command: (...args: any[]) => Promise<any>, thisArg: any, ...params: any[]) {
+    const errorMessage = params[params.length - 1];
     return command.call(thisArg, ...params).catch((err: string | Error) => {
         const error = typeof err === 'string' ? new Error(err) : err;
-        vscode.window.showErrorMessage(error.message);
+        let msg = error.message;
```
[the remark this answers is not in the document]
Comment (lstocchi) [reply src/extension.ts]: well this PR just improved the way the error messages are built, trying to make them nicely. 
It was already assumed in the current implementation that error had a 'message' property. Are there any other kind of response we can receive from the server that are different from a string or an error?

File: src/extension.ts (hunk 1 above)
Comment (lstocchi) [reply src/extension.ts]: I pass the string to this method voluntarily inside the registerCommands, so right now it will work without any check but I can add it easily.

File: src/extension.ts (hunk 3 above)
Comment (lstocchi) [reply src/extension.ts]: I left this empty because there is no way it can fail. It just read from a Map in serverExplorer. It's going to fail only if the Map is not populated but in that case you could not call this action. btw we can add a message here easily too

File: src/extension.ts (hunk 2 above)
Comment (lstocchi) [reply src/extension.ts]: Most of the time string messages are generated by the extension itself while error objects from the server (e.g timeout) so it was a way to display the error nicely, but looking at the code better the label can work with 'Extension backend error' added in both cases.

File: src/extension.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (adietish) [reply src/extension.ts]: I dont know if such responses exist, I just know that it would blow up in this case. In a typed language you'd normally make sure your cast is ok, wont blow up.

[the remark this answers is not in the document]
Comment (jrichter1) [reply src/extension.ts]: So was is the original assumption: 
You can get to this clause by either rejecting a promise, or throwing an error.
 -  Throw clauses only take Error objects as arguments, so the only way to have an empty error message is to create a ```new Error()``` error without one
 - Rejecting can be done with pretty much anything a promise can return, but honestly, we've never used anything but strings

**Comment by adietish** [comment]
@lstocchi can you please rebase this?

**Comment by adietish** [comment]
@lstocchi dare to please rebase this (again - required apparently since we merge your other PRs), please?
